import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "@/app/[lang]/providers";
import { Locale, i18n } from "@/i18n.config";
import { Navbar } from "../components/navbar";

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: Locale };
}) {
  return (
    <html
      lang={params.lang}
      className={`$scroll-smooth`}
      suppressHydrationWarning
    >
      <link
        rel="icon"
        href="https://static1.srcdn.com/wordpress/wp-content/uploads/2023/04/lightning_mcqueen_on_a_racetrack_in_cars.jpg"
        sizes="any"
      />
      <body className={inter.className}>
        <Providers
          themeProps={{
            attribute: "class",
            defaultTheme: "dark",
            children: children,
          }}
        >
          <main className="h-min-screen   dark:bg-black bg-white  dark:bg-grid-white/[0.2] bg-grid-black/[0.2] relative flex items-center justify-center">
            {/* Radial gradient for the container to give a faded look */}
            <div className="absolute pointer-events-none inset-0 flex items-center justify-center dark:bg-black bg-white [mask-image:radial-gradient(ellipse_at_center,transparent_20%,black)]"></div>
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
